window.PORTFOLIO_LAYOUT = {
  "designWidth": 1440,
  "pageHeight": 22282,
  "items": [
    {
      "id": "work-01",
      "title": "My Sister's Baby",
      "caption": "My Sister's Baby — L / GLARC.",
      "src": "assets/work-01.jpg",
      "hoverSrc": "",
      "type": "image",
      "clickable": false,
      "link": "",
      "showCaption": true,
      "x": 42,
      "y": 260,
      "width": 1008,
      "z": 1,
      "rotation": 0,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    },
    {
      "id": "work-02",
      "title": "Marilyn Monroe — All of Us",
      "caption": "Marilyn Monroe — All of Us — L / Radical Documents.",
      "src": "assets/work-02.jpg",
      "hoverSrc": "",
      "type": "image",
      "clickable": false,
      "link": "",
      "showCaption": true,
      "x": 649,
      "y": 1119,
      "width": 749,
      "z": 2,
      "rotation": 0,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    },
    {
      "id": "work-03",
      "title": "Anarchy 99 mixtape",
      "caption": "Anarchy 99 mixtape.",
      "src": "assets/work-03.jpg",
      "hoverSrc": "",
      "type": "image",
      "clickable": false,
      "link": "",
      "showCaption": true,
      "x": 130,
      "y": 2013,
      "width": 1181,
      "z": 3,
      "rotation": 0,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    },
    {
      "id": "work-04",
      "title": "Performing live",
      "caption": "Performing live.",
      "src": "assets/work-04.jpg",
      "hoverSrc": "assets/work-04-hover.jpg",
      "type": "image",
      "clickable": false,
      "link": "",
      "showCaption": true,
      "x": 42,
      "y": 2847,
      "width": 691,
      "z": 4,
      "rotation": 0,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    },
    {
      "id": "work-05",
      "title": "Uri Geller poster",
      "caption": "Uri Geller poster.",
      "src": "assets/work-05.jpg",
      "hoverSrc": "",
      "type": "image",
      "clickable": false,
      "link": "",
      "showCaption": true,
      "x": 750,
      "y": 3952,
      "width": 648,
      "z": 5,
      "rotation": 0,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    },
    {
      "id": "work-06",
      "title": "Screenprint",
      "caption": "Screenprint.",
      "src": "assets/work-06.jpg",
      "hoverSrc": "",
      "type": "image",
      "clickable": false,
      "link": "",
      "showCaption": true,
      "x": 86,
      "y": 4983,
      "width": 1267,
      "z": 6,
      "rotation": 0,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    },
    {
      "id": "work-07",
      "title": "Molecule collage",
      "caption": "Molecule collage.",
      "src": "assets/work-07.jpg",
      "hoverSrc": "",
      "type": "image",
      "clickable": false,
      "link": "",
      "showCaption": true,
      "x": 42,
      "y": 6041,
      "width": 893,
      "z": 7,
      "rotation": 0,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    },
    {
      "id": "work-08",
      "title": "Me in my flat",
      "caption": "Me in my flat.",
      "src": "assets/work-08.jpg",
      "hoverSrc": "assets/work-08-hover.jpg",
      "type": "image",
      "clickable": false,
      "link": "",
      "showCaption": true,
      "x": 779,
      "y": 6835,
      "width": 619,
      "z": 8,
      "rotation": 0,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    },
    {
      "id": "work-09",
      "title": "Poems",
      "caption": "Poems.",
      "src": "assets/work-09.jpg",
      "hoverSrc": "",
      "type": "image",
      "clickable": false,
      "link": "",
      "showCaption": true,
      "x": 360,
      "y": 7805,
      "width": 720,
      "z": 9,
      "rotation": 0,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    },
    {
      "id": "work-10",
      "title": "A Love Supreme",
      "caption": "A Love Supreme — Radiophrenia.",
      "src": "assets/work-10.jpg",
      "hoverSrc": "",
      "type": "image",
      "clickable": false,
      "link": "",
      "showCaption": true,
      "x": 42,
      "y": 8830,
      "width": 1210,
      "z": 10,
      "rotation": 0,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    },
    {
      "id": "work-11",
      "title": "I'm Sorry",
      "caption": "I'm Sorry — magic book.",
      "src": "assets/work-11.jpg",
      "hoverSrc": "",
      "type": "image",
      "clickable": false,
      "link": "",
      "showCaption": true,
      "x": 793,
      "y": 9711,
      "width": 605,
      "z": 11,
      "rotation": 0,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    },
    {
      "id": "work-12",
      "title": "I Love Ass t-shirt",
      "caption": "I Love Ass t-shirt.",
      "src": "assets/work-12.jpg",
      "hoverSrc": "assets/work-12-hover.jpg",
      "type": "image",
      "clickable": false,
      "link": "",
      "showCaption": true,
      "x": 324,
      "y": 10663,
      "width": 792,
      "z": 12,
      "rotation": 0,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    },
    {
      "id": "work-13",
      "title": "Scanned monk",
      "caption": "Scanned monk.",
      "src": "assets/work-13.jpg",
      "hoverSrc": "",
      "type": "image",
      "clickable": false,
      "link": "",
      "showCaption": true,
      "x": 42,
      "y": 11600,
      "width": 562,
      "z": 13,
      "rotation": 0,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    },
    {
      "id": "work-14",
      "title": "Notebook scan",
      "caption": "Notebook scan.",
      "src": "assets/work-14.jpg",
      "hoverSrc": "",
      "type": "image",
      "clickable": false,
      "link": "",
      "showCaption": true,
      "x": 347,
      "y": 12538,
      "width": 1051,
      "z": 14,
      "rotation": 0,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    },
    {
      "id": "work-15",
      "title": "Human Blockhead",
      "caption": "Human Blockhead — performance still.",
      "src": "assets/work-15.jpg",
      "hoverSrc": "",
      "type": "image",
      "clickable": false,
      "link": "",
      "showCaption": true,
      "x": 79,
      "y": 13428,
      "width": 1282,
      "z": 15,
      "rotation": 0,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    },
    {
      "id": "work-16",
      "title": "Gig video",
      "caption": "Gig video.",
      "src": "assets/work-16.gif",
      "hoverSrc": "",
      "type": "gif",
      "clickable": false,
      "link": "",
      "showCaption": true,
      "x": 42,
      "y": 14352,
      "width": 1109,
      "z": 16,
      "rotation": 0,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    },
    {
      "id": "work-17",
      "title": "Magic video",
      "caption": "Magic video.",
      "src": "assets/work-17.jpg",
      "hoverSrc": "",
      "type": "video",
      "clickable": false,
      "link": "",
      "showCaption": true,
      "x": 419,
      "y": 15121,
      "width": 979,
      "z": 17,
      "rotation": 0,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    },
    {
      "id": "work-18",
      "title": "Clown noses",
      "caption": "Clown noses.",
      "src": "assets/work-18.jpg",
      "hoverSrc": "assets/work-18-hover.jpg",
      "type": "image",
      "clickable": false,
      "link": "",
      "showCaption": true,
      "x": 302,
      "y": 15817,
      "width": 835,
      "z": 18,
      "rotation": 0,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    },
    {
      "id": "work-19",
      "title": "Chandelier photos",
      "caption": "Chandelier photos.",
      "src": "assets/work-19.jpg",
      "hoverSrc": "",
      "type": "image",
      "clickable": false,
      "link": "",
      "showCaption": true,
      "x": 736,
      "y": 16797,
      "width": 662,
      "z": 19,
      "rotation": 0,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    },
    {
      "id": "work-20",
      "title": "Photos from around the flat",
      "caption": "Photos from around the flat.",
      "src": "assets/work-20.jpg",
      "hoverSrc": "",
      "type": "image",
      "clickable": false,
      "link": "",
      "showCaption": true,
      "x": 42,
      "y": 17410,
      "width": 1066,
      "z": 20,
      "rotation": 0,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    },
    {
      "id": "work-21",
      "title": "Scanned poetry book",
      "caption": "Scanned poetry book.",
      "src": "assets/work-21.jpg",
      "hoverSrc": "",
      "type": "image",
      "clickable": false,
      "link": "",
      "showCaption": true,
      "x": 346,
      "y": 18311,
      "width": 749,
      "z": 21,
      "rotation": 0,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    },
    {
      "id": "work-22",
      "title": "Scanned receipt poems",
      "caption": "Scanned receipt poems.",
      "src": "assets/work-22.jpg",
      "hoverSrc": "",
      "type": "image",
      "clickable": false,
      "link": "",
      "showCaption": true,
      "x": 836,
      "y": 18986,
      "width": 562,
      "z": 22,
      "rotation": 0,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    },
    {
      "id": "work-23",
      "title": "Exhibition on my table",
      "caption": "Exhibition on my table.",
      "src": "assets/work-23.jpg",
      "hoverSrc": "",
      "type": "image",
      "clickable": false,
      "link": "",
      "showCaption": true,
      "x": 42,
      "y": 19529,
      "width": 950,
      "z": 23,
      "rotation": 0,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    },
    {
      "id": "work-24",
      "title": "Sketchbook drawings",
      "caption": "Sketchbook drawings.",
      "src": "assets/work-24.jpg",
      "hoverSrc": "",
      "type": "image",
      "clickable": false,
      "link": "",
      "showCaption": true,
      "x": 144,
      "y": 20347,
      "width": 1152,
      "z": 24,
      "rotation": 0,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    },
    {
      "id": "work-25",
      "title": "Spoon flag",
      "caption": "Spoon flag.",
      "src": "assets/work-25.jpg",
      "hoverSrc": "",
      "type": "image",
      "clickable": false,
      "link": "",
      "showCaption": true,
      "x": 764,
      "y": 21308,
      "width": 634,
      "z": 25,
      "rotation": 0,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    }
  ],
  "pageStyle": {
    "background": "#ffffff"
  },
  "texts": [
    {
      "id": "text-site-name",
      "role": "siteName",
      "text": "Jack Paton",
      "link": "index.html",
      "newTab": false,
      "x": 34,
      "y": 24,
      "width": 360,
      "z": 100,
      "fontFamily": "Arial, Helvetica, sans-serif",
      "fontSize": 31,
      "color": "#111111",
      "background": "#ffffff",
      "backgroundEnabled": false,
      "fontWeight": 400,
      "italic": false,
      "underline": false,
      "align": "left",
      "lineHeight": 1.0,
      "letterSpacing": -1.0,
      "rotation": 0,
      "opacity": 1
    },
    {
      "id": "text-nav-gigs",
      "role": "nav",
      "text": "gigs",
      "link": "gigs.html",
      "newTab": false,
      "x": 1030,
      "y": 30,
      "width": 70,
      "z": 100,
      "fontFamily": "Arial, Helvetica, sans-serif",
      "fontSize": 15,
      "color": "#111111",
      "background": "#ffffff",
      "backgroundEnabled": false,
      "fontWeight": 400,
      "italic": false,
      "underline": false,
      "align": "left",
      "lineHeight": 1.2,
      "letterSpacing": 0,
      "rotation": 0,
      "opacity": 1
    },
    {
      "id": "text-nav-about",
      "role": "nav",
      "text": "about",
      "link": "about.html",
      "newTab": false,
      "x": 1110,
      "y": 30,
      "width": 70,
      "z": 100,
      "fontFamily": "Arial, Helvetica, sans-serif",
      "fontSize": 15,
      "color": "#111111",
      "background": "#ffffff",
      "backgroundEnabled": false,
      "fontWeight": 400,
      "italic": false,
      "underline": false,
      "align": "left",
      "lineHeight": 1.2,
      "letterSpacing": 0,
      "rotation": 0,
      "opacity": 1
    },
    {
      "id": "text-nav-cv",
      "role": "nav",
      "text": "cv",
      "link": "cv.html",
      "newTab": false,
      "x": 1190,
      "y": 30,
      "width": 40,
      "z": 100,
      "fontFamily": "Arial, Helvetica, sans-serif",
      "fontSize": 15,
      "color": "#111111",
      "background": "#ffffff",
      "backgroundEnabled": false,
      "fontWeight": 400,
      "italic": false,
      "underline": false,
      "align": "left",
      "lineHeight": 1.2,
      "letterSpacing": 0,
      "rotation": 0,
      "opacity": 1
    },
    {
      "id": "text-nav-contact",
      "role": "nav",
      "text": "contact",
      "link": "mailto:YOUR-EMAIL-HERE",
      "newTab": false,
      "x": 1245,
      "y": 30,
      "width": 120,
      "z": 100,
      "fontFamily": "Arial, Helvetica, sans-serif",
      "fontSize": 15,
      "color": "#111111",
      "background": "#ffffff",
      "backgroundEnabled": false,
      "fontWeight": 400,
      "italic": false,
      "underline": false,
      "align": "left",
      "lineHeight": 1.2,
      "letterSpacing": 0,
      "rotation": 0,
      "opacity": 1
    },
    {
      "id": "text-intro",
      "role": "intro",
      "text": "Performance, music, magic, poems, films, posters and other things. Scroll down.",
      "link": "",
      "newTab": false,
      "x": 34,
      "y": 82,
      "width": 650,
      "z": 100,
      "fontFamily": "Arial, Helvetica, sans-serif",
      "fontSize": 15,
      "color": "#111111",
      "background": "#ffffff",
      "backgroundEnabled": false,
      "fontWeight": 400,
      "italic": false,
      "underline": false,
      "align": "left",
      "lineHeight": 1.35,
      "letterSpacing": 0,
      "rotation": 0,
      "opacity": 1
    },
    {
      "id": "text-footer",
      "role": "footer",
      "text": "© 2026 Jack Paton",
      "link": "",
      "newTab": false,
      "x": 34,
      "y": 22247,
      "width": 300,
      "z": 100,
      "fontFamily": "Arial, Helvetica, sans-serif",
      "fontSize": 12,
      "color": "#686868",
      "background": "#ffffff",
      "backgroundEnabled": false,
      "fontWeight": 400,
      "italic": false,
      "underline": false,
      "align": "left",
      "lineHeight": 1.2,
      "letterSpacing": 0,
      "rotation": 0,
      "opacity": 1
    },
    {
      "id": "text-back-top",
      "role": "footer",
      "text": "back to top",
      "link": "#top",
      "newTab": false,
      "x": 1280,
      "y": 22247,
      "width": 130,
      "z": 100,
      "fontFamily": "Arial, Helvetica, sans-serif",
      "fontSize": 12,
      "color": "#686868",
      "background": "#ffffff",
      "backgroundEnabled": false,
      "fontWeight": 400,
      "italic": false,
      "underline": false,
      "align": "right",
      "lineHeight": 1.2,
      "letterSpacing": 0,
      "rotation": 0,
      "opacity": 1
    }
  ]
};
