window.PORTFOLIO_LAYOUT = {
  "designWidth": 1440,
  "pageHeight": 10000,
  "items": [
    {
      "id": "work-01",
      "title": "My Sister's Baby",
      "caption": "still life still life still life still life still life still life still life still life still life still life still life still life still life still life still life still life still life still life ",
      "src": "Jack Day 2-90.jpg",
      "hoverSrc": "",
      "type": "image",
      "clickable": false,
      "link": "",
      "showCaption": true,
      "x": 748,
      "y": 339,
      "width": 600,
      "z": 107,
      "rotation": 1,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    },
    {
      "id": "work-02",
      "title": "Marilyn Monroe — All of Us",
      "caption": "MY SISTER'S BABY— GLARC",
      "src": "a3543726286_10.jpg",
      "hoverSrc": "",
      "type": "image",
      "clickable": false,
      "link": "",
      "showCaption": true,
      "x": 25,
      "y": 1242,
      "width": 449,
      "z": 109,
      "rotation": 2,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    },
    {
      "id": "work-03",
      "title": "Anarchy 99 mixtape",
      "caption": "",
      "src": "20250927-180348.jpg",
      "hoverSrc": "",
      "type": "image",
      "clickable": false,
      "link": "",
      "showCaption": true,
      "x": 973,
      "y": 2331,
      "width": 348,
      "z": 104,
      "rotation": 0,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    },
    {
      "id": "work-04",
      "title": "Performing live",
      "caption": "",
      "src": "sperm.jpg",
      "hoverSrc": "",
      "type": "image",
      "clickable": false,
      "link": "https://www.youtube.com/watch?v=NcV3_INcPbg",
      "showCaption": true,
      "x": 0,
      "y": 15,
      "width": 589,
      "z": 4,
      "rotation": 359,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    },
    {
      "id": "work-05",
      "title": "Uri Geller poster",
      "caption": "Uri Geller poster.",
      "src": "Screenshot 2026-03-18 at 00.38.46.png",
      "hoverSrc": "",
      "type": "image",
      "clickable": false,
      "link": "",
      "showCaption": true,
      "x": 117,
      "y": 1756,
      "width": 827,
      "z": 5,
      "rotation": 0,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    },
    {
      "id": "item-1786134352298",
      "title": "New item 26",
      "caption": "",
      "src": "20250927-180636.jpg",
      "hoverSrc": "",
      "type": "image",
      "clickable": false,
      "link": "",
      "showCaption": false,
      "x": 578,
      "y": 1062,
      "width": 367,
      "z": 110,
      "rotation": 0,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    },
    {
      "id": "item-1786134435836",
      "title": "New item 28",
      "caption": "",
      "src": "Screenshot 2026-03-18 at 00.37.56.png",
      "hoverSrc": "",
      "type": "image",
      "clickable": false,
      "link": "",
      "showCaption": false,
      "x": 899,
      "y": 818,
      "width": 541,
      "z": 103,
      "rotation": 358,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    },
    {
      "id": "item-1786134860494",
      "title": "New item 29",
      "caption": "",
      "src": "Screenshot 2026-08-07 at 21.30.20.png",
      "hoverSrc": "",
      "type": "image",
      "clickable": false,
      "link": "",
      "showCaption": false,
      "x": 1000,
      "y": 1786,
      "width": 250,
      "z": 106,
      "rotation": 0,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    }
  ],
  "pageStyle": {
    "background": "#ffffff"
  },
  "texts": [
    {
      "id": "text-site-name",
      "role": "siteName",
      "text": "Jackpaton.com",
      "link": "index.html",
      "newTab": false,
      "x": 540,
      "y": 113,
      "width": 47,
      "z": 112,
      "fontFamily": "Arial, Helvetica, sans-serif",
      "fontSize": 65,
      "color": "#002aff",
      "background": "#ffffff",
      "backgroundEnabled": false,
      "fontWeight": 400,
      "italic": false,
      "underline": false,
      "align": "left",
      "lineHeight": 1,
      "letterSpacing": 0,
      "rotation": 0,
      "opacity": 1
    },
    {
      "id": "text-nav-gigs",
      "role": "nav",
      "text": "gigs",
      "link": "gigs.html",
      "newTab": false,
      "x": 1005,
      "y": 44,
      "width": 70,
      "z": 100,
      "fontFamily": "Arial, Helvetica, sans-serif",
      "fontSize": 15,
      "color": "#111111",
      "background": "#ffffff",
      "backgroundEnabled": false,
      "fontWeight": 400,
      "italic": false,
      "underline": false,
      "align": "left",
      "lineHeight": 1.2,
      "letterSpacing": 0,
      "rotation": 0,
      "opacity": 1
    },
    {
      "id": "text-nav-about",
      "role": "nav",
      "text": "about",
      "link": "about.html",
      "newTab": false,
      "x": 1094,
      "y": 45,
      "width": 70,
      "z": 100,
      "fontFamily": "Arial, Helvetica, sans-serif",
      "fontSize": 15,
      "color": "#111111",
      "background": "#ffffff",
      "backgroundEnabled": false,
      "fontWeight": 400,
      "italic": false,
      "underline": false,
      "align": "left",
      "lineHeight": 1.2,
      "letterSpacing": 0,
      "rotation": 0,
      "opacity": 1
    },
    {
      "id": "text-nav-cv",
      "role": "nav",
      "text": "cv",
      "link": "cv.html",
      "newTab": false,
      "x": 1192,
      "y": 47,
      "width": 40,
      "z": 100,
      "fontFamily": "Arial, Helvetica, sans-serif",
      "fontSize": 15,
      "color": "#111111",
      "background": "#ffffff",
      "backgroundEnabled": false,
      "fontWeight": 400,
      "italic": false,
      "underline": false,
      "align": "left",
      "lineHeight": 1.2,
      "letterSpacing": 0,
      "rotation": 0,
      "opacity": 1
    },
    {
      "id": "text-nav-contact",
      "role": "nav",
      "text": "contact",
      "link": "mailto:YOUR-EMAIL-HERE",
      "newTab": false,
      "x": 1263,
      "y": 48,
      "width": 120,
      "z": 100,
      "fontFamily": "Arial, Helvetica, sans-serif",
      "fontSize": 15,
      "color": "#111111",
      "background": "#ffffff",
      "backgroundEnabled": false,
      "fontWeight": 400,
      "italic": false,
      "underline": false,
      "align": "left",
      "lineHeight": 1.2,
      "letterSpacing": 0,
      "rotation": 0,
      "opacity": 1
    },
    {
      "id": "text-intro",
      "role": "intro",
      "text": "I MY WHOLE LIFE \nI MY WHOLE LIFE\nI MY WHOLE LIFE I\nMY WHOLE LIFE I\nMY WHOLE LIFE I\n\n",
      "link": "",
      "newTab": false,
      "x": 640,
      "y": 102,
      "width": 184,
      "z": 100,
      "fontFamily": "Arial, Helvetica, sans-serif",
      "fontSize": 18,
      "color": "#ff0000",
      "background": "#ffffff",
      "backgroundEnabled": false,
      "fontWeight": 400,
      "italic": false,
      "underline": false,
      "align": "left",
      "lineHeight": 1.35,
      "letterSpacing": 0,
      "rotation": 0,
      "opacity": 1
    },
    {
      "id": "text-footer",
      "role": "footer",
      "text": "© 2026 Jack Paton",
      "link": "",
      "newTab": false,
      "x": 34,
      "y": 22247,
      "width": 300,
      "z": 100,
      "fontFamily": "Arial, Helvetica, sans-serif",
      "fontSize": 12,
      "color": "#686868",
      "background": "#ffffff",
      "backgroundEnabled": false,
      "fontWeight": 400,
      "italic": false,
      "underline": false,
      "align": "left",
      "lineHeight": 1.2,
      "letterSpacing": 0,
      "rotation": 0,
      "opacity": 1
    },
    {
      "id": "text-back-top",
      "role": "footer",
      "text": "back to top",
      "link": "#top",
      "newTab": false,
      "x": 1280,
      "y": 22247,
      "width": 130,
      "z": 100,
      "fontFamily": "Arial, Helvetica, sans-serif",
      "fontSize": 12,
      "color": "#686868",
      "background": "#ffffff",
      "backgroundEnabled": false,
      "fontWeight": 400,
      "italic": false,
      "underline": false,
      "align": "right",
      "lineHeight": 1.2,
      "letterSpacing": 0,
      "rotation": 0,
      "opacity": 1
    },
    {
      "id": "text-1786144615842",
      "role": "text",
      "text": "\nYOU AND ME\nARE LIKE\nLAND AND SEA\nWE MEET AT BEACHES\n                                                                                                                                   SOMETIMES\n",
      "link": "",
      "newTab": false,
      "x": 521,
      "y": 1616,
      "width": 785,
      "z": 111,
      "fontFamily": "Arial, Helvetica, sans-serif",
      "fontSize": 18,
      "color": "#ff0000",
      "background": "#002aff",
      "backgroundEnabled": false,
      "fontWeight": 400,
      "italic": false,
      "underline": false,
      "align": "left",
      "lineHeight": 1.2,
      "letterSpacing": 0,
      "rotation": 0,
      "opacity": 1
    }
  ]
};
