window.PORTFOLIO_LAYOUT = {
  "designWidth": 1440,
  "pageHeight": 10000,
  "items": [
    {
      "id": "work-01",
      "title": "My Sister's Baby",
      "caption": "still life still life still life still life still life still life still life still life still life still life still life still life still life still life still life still life still life still life ",
      "src": "Jack Day 2-90.jpg",
      "hoverSrc": "",
      "type": "image",
      "clickable": false,
      "link": "",
      "showCaption": true,
      "x": 791,
      "y": 511,
      "width": 600,
      "z": 107,
      "rotation": 1,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    },
    {
      "id": "work-02",
      "title": "Marilyn Monroe — All of Us",
      "caption": "MY SISTER'S BABY— GLARC",
      "src": "https://res.cloudinary.com/ftbzogfu/image/upload/v1786296233/a3543726286_10.jpg",
      "hoverSrc": "",
      "type": "image",
      "clickable": false,
      "link": "",
      "showCaption": true,
      "x": 948,
      "y": 1733,
      "width": 450,
      "z": 109,
      "rotation": 2,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    },
    {
      "id": "work-03",
      "title": "Anarchy 99 mixtape",
      "caption": "",
      "src": "https://res.cloudinary.com/ftbzogfu/image/upload/v1786296817/motor_copy555.jpg",
      "hoverSrc": "",
      "type": "image",
      "clickable": false,
      "link": "",
      "showCaption": true,
      "x": 30,
      "y": 2673,
      "width": 824,
      "z": 120,
      "rotation": 0,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    },
    {
      "id": "work-04",
      "title": "Performing live",
      "caption": "",
      "src": "https://res.cloudinary.com/ftbzogfu/image/upload/v1786296233/sperm.jpg",
      "hoverSrc": "",
      "type": "image",
      "clickable": false,
      "link": "https://www.youtube.com/watch?v=NcV3_INcPbg",
      "showCaption": true,
      "x": 0,
      "y": 356,
      "width": 624,
      "z": 119,
      "rotation": 359,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    },
    {
      "id": "work-05",
      "title": "Uri Geller poster",
      "caption": "Uri Geller poster.",
      "src": "https://res.cloudinary.com/ftbzogfu/image/upload/v1786297069/2026-03-12_19-37_2.jpg",
      "hoverSrc": "",
      "type": "image",
      "clickable": false,
      "link": "",
      "showCaption": true,
      "x": 63,
      "y": 1857,
      "width": 436,
      "z": 5,
      "rotation": 0,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    },
    {
      "id": "item-1786134352298",
      "title": "New item 26",
      "caption": "",
      "src": "https://res.cloudinary.com/ftbzogfu/image/upload/v1786296712/20250927-180636.jpg",
      "hoverSrc": "",
      "type": "image",
      "clickable": false,
      "link": "",
      "showCaption": false,
      "x": 945,
      "y": 2319,
      "width": 431,
      "z": 110,
      "rotation": 2,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    },
    {
      "id": "item-1786134435836",
      "title": "New item 28",
      "caption": "",
      "src": "https://res.cloudinary.com/ftbzogfu/image/upload/v1786297781/20260228-185109.jpg",
      "hoverSrc": "",
      "type": "image",
      "clickable": false,
      "link": "",
      "showCaption": false,
      "x": 834,
      "y": 1052,
      "width": 541,
      "z": 103,
      "rotation": 358,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    },
    {
      "id": "item-1786134860494",
      "title": "New item 29",
      "caption": "",
      "src": "https://res.cloudinary.com/ftbzogfu/image/upload/v1786297307/Screenshot_2026-08-07_at_21.30.20.png",
      "hoverSrc": "",
      "type": "image",
      "clickable": false,
      "link": "",
      "showCaption": false,
      "x": 576,
      "y": 2129,
      "width": 307,
      "z": 106,
      "rotation": 0,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    },
    {
      "id": "item-1786295566289",
      "title": "New item 10",
      "caption": "",
      "src": "https://res.cloudinary.com/ftbzogfu/image/upload/v1786296237/hammer.png",
      "hoverSrc": "",
      "type": "image",
      "clickable": false,
      "link": "",
      "showCaption": false,
      "x": 43,
      "y": 4271,
      "width": 709,
      "z": 114,
      "rotation": 0,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    },
    {
      "id": "item-1786297398008",
      "title": "New item 10",
      "caption": "",
      "src": "https://res.cloudinary.com/ftbzogfu/image/upload/v1786296175/IMG_2417.jpg",
      "hoverSrc": "",
      "type": "image",
      "clickable": false,
      "link": "",
      "showCaption": false,
      "x": 49,
      "y": 1252,
      "width": 750,
      "z": 122,
      "rotation": 359,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    },
    {
      "id": "item-1786298003278",
      "title": "New item 11",
      "caption": "",
      "src": "https://res.cloudinary.com/ftbzogfu/image/upload/v1786297082/411B892F-F12D-447F-B9E7-3AFB9FF62BAA.jpg",
      "hoverSrc": "",
      "type": "image",
      "clickable": false,
      "link": "",
      "showCaption": false,
      "x": 962,
      "y": 3006,
      "width": 405,
      "z": 124,
      "rotation": 0,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    },
    {
      "id": "item-1786298048568",
      "title": "New item 12",
      "caption": "",
      "src": "https://res.cloudinary.com/ftbzogfu/image/upload/v1786296767/hory_copy.jpg",
      "hoverSrc": "",
      "type": "image",
      "clickable": false,
      "link": "",
      "showCaption": false,
      "x": 0,
      "y": 3330,
      "width": 1002,
      "z": 117,
      "rotation": 0,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    },
    {
      "id": "item-1786298129979",
      "title": "New item 13",
      "caption": "",
      "src": "https://res.cloudinary.com/ftbzogfu/image/upload/v1786296750/20260116-203804.jpg",
      "hoverSrc": "",
      "type": "image",
      "clickable": false,
      "link": "",
      "showCaption": false,
      "x": 862,
      "y": 4170,
      "width": 500,
      "z": 118,
      "rotation": 0,
      "opacity": 1,
      "captionFontFamily": "Arial, Helvetica, sans-serif",
      "captionFontSize": 12,
      "captionColor": "#111111",
      "captionAlign": "left"
    }
  ],
  "pageStyle": {
    "background": "#ffffff"
  },
  "texts": [
    {
      "id": "text-site-name",
      "role": "siteName",
      "text": "Jackpaton.com",
      "link": "index.html",
      "newTab": false,
      "x": 550,
      "y": 25,
      "width": 20,
      "z": 121,
      "fontFamily": "Arial, Helvetica, sans-serif",
      "fontSize": 65,
      "color": "#002aff",
      "background": "#ffffff",
      "backgroundEnabled": false,
      "fontWeight": 400,
      "italic": false,
      "underline": false,
      "align": "left",
      "lineHeight": 1,
      "letterSpacing": 0,
      "rotation": 0,
      "opacity": 1
    },
    {
      "id": "text-nav-gigs",
      "role": "nav",
      "text": "gigs",
      "link": "gigs.html",
      "newTab": false,
      "x": 1005,
      "y": 44,
      "width": 70,
      "z": 100,
      "fontFamily": "Arial, Helvetica, sans-serif",
      "fontSize": 15,
      "color": "#111111",
      "background": "#ffffff",
      "backgroundEnabled": false,
      "fontWeight": 400,
      "italic": false,
      "underline": false,
      "align": "left",
      "lineHeight": 1.2,
      "letterSpacing": 0,
      "rotation": 0,
      "opacity": 1
    },
    {
      "id": "text-nav-about",
      "role": "nav",
      "text": "about",
      "link": "about.html",
      "newTab": false,
      "x": 1094,
      "y": 45,
      "width": 70,
      "z": 100,
      "fontFamily": "Arial, Helvetica, sans-serif",
      "fontSize": 15,
      "color": "#111111",
      "background": "#ffffff",
      "backgroundEnabled": false,
      "fontWeight": 400,
      "italic": false,
      "underline": false,
      "align": "left",
      "lineHeight": 1.2,
      "letterSpacing": 0,
      "rotation": 0,
      "opacity": 1
    },
    {
      "id": "text-nav-cv",
      "role": "nav",
      "text": "cv",
      "link": "cv.html",
      "newTab": false,
      "x": 1192,
      "y": 47,
      "width": 40,
      "z": 100,
      "fontFamily": "Arial, Helvetica, sans-serif",
      "fontSize": 15,
      "color": "#111111",
      "background": "#ffffff",
      "backgroundEnabled": false,
      "fontWeight": 400,
      "italic": false,
      "underline": false,
      "align": "left",
      "lineHeight": 1.2,
      "letterSpacing": 0,
      "rotation": 0,
      "opacity": 1
    },
    {
      "id": "text-nav-contact",
      "role": "nav",
      "text": "contact",
      "link": "mailto:YOUR-EMAIL-HERE",
      "newTab": false,
      "x": 1263,
      "y": 48,
      "width": 120,
      "z": 100,
      "fontFamily": "Arial, Helvetica, sans-serif",
      "fontSize": 15,
      "color": "#111111",
      "background": "#ffffff",
      "backgroundEnabled": false,
      "fontWeight": 400,
      "italic": false,
      "underline": false,
      "align": "left",
      "lineHeight": 1.2,
      "letterSpacing": 0,
      "rotation": 0,
      "opacity": 1
    },
    {
      "id": "text-intro",
      "role": "intro",
      "text": "I MY WHOLE LIFE \nI MY WHOLE LIFE\nI MY WHOLE LIFE I\nMY WHOLE LIFE I\nMY WHOLE LIFE I\n\n",
      "link": "",
      "newTab": false,
      "x": 1038,
      "y": 170,
      "width": 184,
      "z": 123,
      "fontFamily": "Arial, Helvetica, sans-serif",
      "fontSize": 16,
      "color": "#ff0000",
      "background": "#ffffff",
      "backgroundEnabled": false,
      "fontWeight": 400,
      "italic": false,
      "underline": false,
      "align": "left",
      "lineHeight": 1.35,
      "letterSpacing": 0,
      "rotation": 0,
      "opacity": 1
    },
    {
      "id": "text-footer",
      "role": "footer",
      "text": "© 2026 Jack Paton",
      "link": "",
      "newTab": false,
      "x": 34,
      "y": 22247,
      "width": 300,
      "z": 100,
      "fontFamily": "Arial, Helvetica, sans-serif",
      "fontSize": 12,
      "color": "#686868",
      "background": "#ffffff",
      "backgroundEnabled": false,
      "fontWeight": 400,
      "italic": false,
      "underline": false,
      "align": "left",
      "lineHeight": 1.2,
      "letterSpacing": 0,
      "rotation": 0,
      "opacity": 1
    },
    {
      "id": "text-back-top",
      "role": "footer",
      "text": "back to top",
      "link": "#top",
      "newTab": false,
      "x": 1280,
      "y": 22247,
      "width": 130,
      "z": 100,
      "fontFamily": "Arial, Helvetica, sans-serif",
      "fontSize": 12,
      "color": "#686868",
      "background": "#ffffff",
      "backgroundEnabled": false,
      "fontWeight": 400,
      "italic": false,
      "underline": false,
      "align": "right",
      "lineHeight": 1.2,
      "letterSpacing": 0,
      "rotation": 0,
      "opacity": 1
    },
    {
      "id": "text-1786144615842",
      "role": "text",
      "text": "\nYOU AND ME\nARE LIKE\nLAND AND SEA\nWE MEET AT BEACHES\n                                                                                                                                   SOMETIMES\n",
      "link": "",
      "newTab": false,
      "x": 71,
      "y": 2700,
      "width": 593,
      "z": 111,
      "fontFamily": "Arial, Helvetica, sans-serif",
      "fontSize": 18,
      "color": "#ff0000",
      "background": "#002aff",
      "backgroundEnabled": false,
      "fontWeight": 400,
      "italic": false,
      "underline": false,
      "align": "left",
      "lineHeight": 1.2,
      "letterSpacing": 0,
      "rotation": 0,
      "opacity": 1
    }
  ]
};
